[package]
name = "fsm"
version = "0.1.0"
authors = ["Chris Patuzzo <chris@patuzzo.co.uk>"]

[dependencies]
prismatic = "0.2.0"
stdweb = "0.4.6"
stdweb-derive = "0.4.0"
serde = "1.0.0"
serde_derive = "1.0.0"

[build-dependencies]
webgl_generator = "0.1.0"
